name: Build and deploy ASP.Net Core app to Azure Web App - anotali

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Build solution
        run: dotnet build ./AnotaLI.sln --configuration Release

      - name: Publish the application
        run: dotnet publish ./AL.WebApi/AL.WebApi.csproj -c Release -o ./myapp # Mantido o caminho para a raiz

      - name: List files in output directory
        run: dir ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
      runs-on: windows-latest
      needs: build
      environment:
        name: "Production"
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      permissions:
        id-token: write

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: .net-app
            path: ./publish # <-- Aqui você está especificando onde o artefato será baixado.

        - name: Check current directory
          run: pwd

        - name: List downloaded files
          run: dir ./publish  # <-- Este comando lista os arquivos no diretório ./publish para verificar se estão corretos.

        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_13CE46608F0647FEB019812AF81C7D5E }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D29035EDD2C14CA085127F67320078B2 }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_59B22C08B79B4168983069F2E5182686 }}

        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v3
          with:
            app-name: "anotali"
            slot-name: "Production"
            package: "./publish"  # <-- Certifique-se de que o diretório está correto