jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Build solution
        run: dotnet build ./AnotaLI.sln --configuration Release

      - name: Publish the application
        run: dotnet publish ./AL.WebApi/AL.WebApi.csproj -c Release -o ./myapp

      - name: List contents of myapp after publish
        run: |
          if (Test-Path -Path "./myapp") {
            Write-Host "Directory myapp exists."
            Write-Host "Contents of myapp:"
            Get-ChildItem -Path "./myapp" -Recurse
          } else {
            Write-Host "Directory myapp does not exist!"
            exit 1
          }

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: List contents after artifact download
        run: |
          Write-Host "Current directory:"
          Get-ChildItem -Path . -Recurse

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_13CE46608F0647FEB019812AF81C7D5E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D29035EDD2C14CA085127F67320078B2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_59B22C08B79B4168983069F2E5182686 }}

      - name: Verify package contents
        run: |
          if (Test-Path -Path "./myapp") {
            Write-Host "Directory myapp exists."
            Write-Host "Contents of myapp:"
            Get-ChildItem -Path "./myapp" -Recurse
          } else {
            Write-Host "Directory myapp does not exist!"
            exit 1
          }

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "anotali"
          slot-name: "Production"
          package: "myapp/**/*" # Ajustado
